version: '2'

services:
  web:
    container_name: nginx-${USERNAME}
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - devcode:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./${USERNAME}.env
    networks:
      - code-network
  php:
    container_name: php-fpm-${USERNAME}
    image: php:fpm
    volumes:
      - devcode:/code
    env_file:
      - ./${USERNAME}.env
    networks:
      - code-network
  code-server:
    container_name: code-server-${USERNAME}
    image: lscr.io/linuxserver/code-server:latest
    volumes:
      - devcode:/config/code
    env_file:
      - ./${USERNAME}.env
    networks:
      - code-network
    ports:
      - "${CODE_PORT}:8443"
    restart: unless-stopped
    environment:
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - TZ=America/New_York
      - DEFAULT_WORKSPACE=/config/code

volumes:
  devcode:


networks:
  code-network:
    driver: bridge
